# Master reference of every function used across modules 0-8 of the GIS in R
# course, with the package it comes from and a single, course-accurate
# definition. Compiled from each module's function_tables/*.csv files (and,
# for module_8, its hardcoded Functions accordions -- module_8 has no
# function_tables/ directory), reconciled against a full audit of every R code
# chunk in modules/module_0 through modules/module_8 to confirm completeness.

library(tidyverse)

gis_functions <-
  tribble(
    ~ package, ~ function_name, ~ definition,
    ".Primitive", "!", "Prefix logical operator (not)",
    ".Primitive", "!=", "Infix relational operator (is not equal to)",
    ".Primitive", "$", "Infix operator that extracts the values associated with a name (RHS) from a recursive object (LHS)",
    ".Primitive", "&", "Infix logical operator (and)",
    ".Primitive", "(...)", "Operator that evaluates the function name on the left-hand-side (LHS) of the opening parentheses using the arguments enclosed by the parentheses",
    ".Primitive", "*", "Infix arithmetic operator (multiply)",
    ".Primitive", "+", "Infix arithmetic operator (addition)",
    ".Primitive", "-", "Infix arithmetic operator (subtract) or prefix negative symbol operator",
    ".Primitive", "/", "Infix arithmetic operator (divide)",
    ".Primitive", ":", "Infix operator that generates a regular sequence of adjacent values",
    ".Primitive", "::", "Infix operator that can be used to access a package environment without attaching the whole package environment to your current session",
    ".Primitive", ":::", "Infix operator that can be used to access a function that is not meant to be exported!",
    ".Primitive", "<", "Infix relational operator (less than)",
    ".Primitive", "<-", "Infix operator that assigns an object on the right-hand-side (RHS) to a name on the left-hand-side (LHS) -- this should be used for global assignments!",
    ".Primitive", "<=", "Infix relational operator (less than or equal to)",
    ".Primitive", "=", "Infix operator that assigns an object on the right-hand-side (RHS) to a name on the left-hand-side (LHS) -- this should not be used for global assignments!",
    ".Primitive", "==", "Infix relational operator (is equal to)",
    ".Primitive", ">", "Infix relational operator (greater than)",
    ".Primitive", ">=", "Infix relational operator (greater than or equal to)",
    ".Primitive", "[...]", "Extraction operator used to index multiple values from a data object (LHS) based on the position or values specified inside the brackets",
    ".Primitive", "[[...]]", "Extraction operator used to index a single value from a data object (LHS) based on the position or values specified inside the brackets",
    ".Primitive", "^", "Infix arithmetic operator (to the power of)",
    ".Primitive", "as.character", "Transform an atomic vector to a character vector",
    ".Primitive", "as.integer", "Transform an atomic vector to an integer vector",
    ".Primitive", "as.numeric", "Transform an atomic vector to a double numeric vector (i.e., decimal numbers)",
    ".Primitive", "attributes", "Generate and print a list that represents the attributes of a data object",
    ".Primitive", "c", "Combine values to form an atomic vector",
    ".Primitive", "ceiling", "Round a numeric vector to an integer value not less than the corresponding elements of x",
    ".Primitive", "class", "Print the class of an object as a one-value character vector",
    ".Primitive", "else", "Used in conjunction with `if`, evaluate a statement when `if` evaluates to FALSE.",
    ".Primitive", "function", "The primitive used to define a custom function.",
    ".Primitive", "if", "If a logical value is TRUE, evaluate a statement",
    ".Primitive", "is.na", "A logical test of whether a value in a vector is [NA]",
    ".Primitive", "list", "Combine multiple objects of any type into a single, recursive, data object",
    ".Primitive", "max", "Return the highest value in a numeric vector (integer or double) as a one-value numeric or integer vector (depending on input)",
    ".Primitive", "min", "Return the lowest value in a numeric vector (integer or double) as a one-value numeric or integer vector (depending on input)",
    ".Primitive", "rep", "Replicate elements of a vector a certain number of times",
    ".Primitive", "return", "Return the results from a given point in a function's body (do not use for the last value!)",
    ".Primitive", "sqrt", "Calculate the square root of a numeric vector",
    ".Primitive", "sum", "Calculate the sum of the values in a numeric vector.",
    ".Primitive", "{...}", "Operator that passes the last operation in `{...}` to the global environment",
    ".Primitive", "|", "Infix logical operator (or)",
    ".Primitive", "~", "The formula operator separates the left- and right-hand sides (LHS and RHS) in a formula.",
    "base", "%in%", "Infix relational operator that tests whether the values on the left-hand-side (LHS) are found within the vector on the right-hand-side (RHS)",
    "base", "as.matrix", "Convert a data frame to a matrix",
    "base", "as.vector", "Coerce a data object (e.g., a matrix) to an atomic vector, stripping its other attributes.",
    "base", "body", "Print the body of an R function",
    "base", "capabilities", "Report the optional features compiled in your R build",
    "base", "colnames", "Assign column names to a matrix, or print assigned column names",
    "base", "cut", "Convert a numeric vector into a factor",
    "base", "data.frame", "Arrange equal-length vectors into a data frame",
    "base", "dim", "Return the dimensions (number of rows and columns, or array dimensions) of a data object.",
    "base", "environment", "Print the environment of a given function",
    "base", "factor", "Convert a character vector to a factor",
    "base", "file.path", "Create a file path by concatenating strings",
    "base", "file.remove", "Delete a file from your hard drive",
    "base", "formals", "Print the formals of an R function",
    "base", "head", "Return the first 6 rows of a data frame (by default)",
    "base", "length", "Determine the length of an object -- for atomic vectors and matrices, this returns the number of values; for lists and data frames, this returns the number of component objects.",
    "base", "levels", "Generate a character vector of factor levels in a factor variable",
    "base", "library", "Attach the package environment for a given package to the current R session",
    "base", "list.files", "List files in a specified folder on your computer's hard drive",
    "base", "list2env", "Assign the items in a list to a specified environment",
    "base", "ls", "Generate a character vector of names in a specified environment (default is the global environment)",
    "base", "matrix", "Generate a matrix object by adding dimensional attributes to an atomic vector",
    "base", "mean", "Generate a one-value double numeric vector that describes the mean of a vector",
    "base", "names", "Get or set the names attribute of an object.",
    "base", "ncol", "Return the number of columns (i.e., variables or list items) in a data frame as a one-value integer vector",
    "base", "nrow", "Return the number of rows (i.e., observations) in a data frame as a one-value integer vector",
    "base", "rm", "Remove a name from a specified environment (default is the global environment)",
    "base", "row.names", "Assign row names to a matrix or data frame, or print assigned row names",
    "base", "search", "Print a character vector of attached objects associated with your current R session",
    "base", "seq", "Generate a numeric vector between a range of values by some increment",
    "base", "source", "Execute a source script (in its entirety)",
    "base", "summary", "Print summary stats for a data object",
    "base", "table", "Count the number of unique observations in an atomic vector",
    "base", "tolower", "Convert a character vector to lowercase",
    "base", "typeof", "Print a one-value character vector that represents how a data object is stored on your computer",
    "base", "unique", "Subset an atomic vector to the unique values in the set",
    "base", "unit", "Set or create a unit object",
    "base", "which", "Determine the position of a value where a logical test evaluates to TRUE",
    "base", "|>", "Infix pipe operator that passes the left-hand side (LHS) as the first argument to the function on the right-hand side (RHS)",
    "bench", "mark", "Benchmark an operation (processing time and memory used)",
    "cols4all", "c4a_gui", "Launch an interactive color-palette explorer (tmap v4's replacement for tmaptools::palette_explorer()).",
    "dplyr", "across", "Apply a function across multiple variables in a data frame",
    "dplyr", "anti_join", "A filtering join that joins a source table to a target table and maintains only records in which the key values *do not* match",
    "dplyr", "arrange", "Sort the rows of a data frame by the values in a variable or variables",
    "dplyr", "bind_cols", "Combine two variables or columns of two tibbles to create a new tibble",
    "dplyr", "bind_rows", "Combine rows of two or more tibbles to create a new tibble",
    "dplyr", "case_when", "Classify or reclassify a vector into two or more  classes based on a series of logical tests",
    "dplyr", "count", "Tabulate the number of observations of each unique value of a column in a data frame and return as a long format tibble",
    "dplyr", "desc", "When used with `arrange()`, this sorts the rows of a data frame by the values of a variable in descending order",
    "dplyr", "distinct", "Subset a data frame by removing duplicate rows",
    "dplyr", "filter", "Subset a data frame by logical condition",
    "dplyr", "full_join", "A mutating join that joins a source table to a target table and maintains all records in both tables, regardless of matching key values",
    "dplyr", "group_by", "Group the data in a data frame by a given variable such that one or more subsequent analyses are run separately on each group",
    "dplyr", "if_any", "Apply a logical test across multiple columns and return TRUE if the test is TRUE for at least one of them (used inside functions like filter()).",
    "dplyr", "if_else", "Classify or reclassify a vector into two classes by applying a logical test and assigning one value if the test evaluates to `TRUE` and another if it evaluates to `FALSE`",
    "dplyr", "inner_join", "A mutating join that joins a source table to a target table and maintains only records with matching key values",
    "dplyr", "join_by", "Specify the key columns within a join function",
    "dplyr", "left_join", "A mutating join that joins a source table to a target table and maintains all records found in the target table, regardless of matching key values",
    "dplyr", "mutate", "Add or modify a column in a data frame",
    "dplyr", "n", "Calculate the number of observations (rows)",
    "dplyr", "na_if", "Convert a value in a vector to NA",
    "dplyr", "pull", "Extract a column from a data frame as a vector",
    "dplyr", "rename", "Change the name assigned to a column in a data frame",
    "dplyr", "row_number", "Generate a sequence of integer values from 1 to the number of rows in a data frame",
    "dplyr", "select", "Subset columns in a data frame by name (without quotes!)",
    "dplyr", "semi_join", "A filtering join that joins a source table to a target table and maintains only records with matching key values",
    "dplyr", "slice", "Subset a data frame by row or rows using the row position(s)",
    "dplyr", "slice_head", "Subset a data frame to the first row (default) or rows",
    "dplyr", "slice_max", "Sort a data frame by a variable and subset to the rows associated with the highest values of that variable",
    "dplyr", "slice_min", "Sort a data frame by a variable and subset to the rows associated with the lowest values of that variable",
    "dplyr", "slice_tail", "Subset a data frame to the last row (default) or rows",
    "dplyr", "summarize", "Calculate one or more summary statistics on a variable or variables in a data frame (often used in conjunction with `group_by()` but may also be used with `.by = ...`)",
    "dplyr", "transmute", "Mutate a data frame while subsetting the columns to those specified in the function",
    "dplyr", "ungroup", "Remove any grouping on a data frame",
    "forcats", "fct_collapse", "Collapse factor levels into manually defined groups",
    "forcats", "fct_recode", "Change factor levels by hand (specify a new factor level or modify an existing level)",
    "forcats", "fct_relevel", "Reorder factor levels by hand",
    "forcats", "fct_reorder", "Reorder factor levels by another variable",
    "forcats", "fct_rev", "Reverse the order of factor levels",
    "ggplot2", "aes", "Define aesthetics",
    "ggplot2", "coord_flip", "Switch the mapping to the horizontal and vertical coordinates",
    "ggplot2", "element_line", "Set the theme for a line element",
    "ggplot2", "element_rect", "Set the theme for a shape element",
    "ggplot2", "element_text", "Set the theme for a text element",
    "ggplot2", "expansion", "Set upper and lower values or proportions to expand an axis by",
    "ggplot2", "facet_wrap", "Split plot into facets",
    "ggplot2", "geom_bar", "Create a bar geometry",
    "ggplot2", "geom_boxplot", "Create a boxplot geometry",
    "ggplot2", "geom_point", "Create a point geometry",
    "ggplot2", "geom_sf", "Add an sf layer to a ggplot",
    "ggplot2", "geom_sf_text", "Add an sf layer to a ggplot as a text",
    "ggplot2", "geom_smooth", "Add a line-of-best-fit geometry",
    "ggplot2", "ggplot", "Set the data and, potentially, the aesthetics of a plot",
    "ggplot2", "ggsave", "Save a ggplot to your computer",
    "ggplot2", "labs", "Add or modify the labels of a plot",
    "ggplot2", "scale_color_manual", "Manually define the colors of a geometry",
    "ggplot2", "scale_fill_brewer", "Fill a geometry with colors from a RColorBrewer palette",
    "ggplot2", "scale_fill_viridis_c", "Add a continuous virdis color scale to a plot",
    "ggplot2", "scale_x_continuous", "Set the scale of the x axis",
    "ggplot2", "scale_y_continuous", "Set the scale of the y axis",
    "ggplot2", "theme", "Define the theme elements of a plot",
    "ggplot2", "theme_bw", "Generate a pre-packaged light background theme for a plot",
    "ggplot2", "theme_set", "Set the ggplot theme for an entire session",
    "ggplot2", "theme_void", "A ggplot theme that contains no axes or panel background",
    "gis_functions.R", "clean_names", "Standardize a shapefile's or data frame's column names to snake_case (course-authored helper in src/r/gis_functions.R).",
    "gis_functions.R", "lonlat_to_utm", "Determine the EPSG code of the UTM zone that contains a given longitude/latitude coordinate (course-authored helper in src/r/gis_functions.R, adapted from Lovelace, Nowosad, and Muenchow's *Geocomputation with R*).",
    "gis_functions.R", "universal_plot_theme", "Apply the course's shared ggplot2 theme to a plot (course-authored helper in src/r/gis_functions.R).",
    "graphics", "plot", "Generate a basic plot of a data object",
    "grDevices", "gray.colors", "Generate a color palette of gray colors",
    "grDevices", "terrain.colors", "Generate a color palette of terrain colors",
    "lobstr", "mem_used", "View the number of bytes used by R in your current session",
    "lobstr", "obj_addr", "Find the location of an object and its children",
    "lobstr", "obj_size", "View the amount of memory allocated to an object in your computer's memory",
    "lobstr", "ref", "View the structure of an object in your computer's memory",
    "lubridate", "as_date", "Convert properly formatted date, stored as a character or datetime vector, to a date class object",
    "lubridate", "dmy", "Convert a date formatted as day, month, year (European date format) to a date class object",
    "lubridate", "month", "Extract the month from a properly formatted date value",
    "lubridate", "now", "Return the current date and time",
    "lubridate", "year", "Extract the year from a properly formatted date value",
    "magrittr", "%>%", "The pipe operator passes the output of the LHS argument to the function on the right",
    "magrittr", "extract", "Extract a value from an atomic vector or list item by position or name",
    "mapview", "npts", "Determine the number of vertices (i.e., nodes or points) in a polygon",
    "microbenchmark", "microbenchmark", "Calculate the time it takes to complete an operation",
    "profmem", "profmem", "Profile the memory used during an operation",
    "profmem", "total", "Determine the total amount of memory allocated during an operation",
    "purrr", "map", "Iterate across a vector and return a list",
    "purrr", "map_dbl", "Iterate across a vector and return a double numeric vector",
    "purrr", "map_dfr", "Iterate across a vector and return a data frame such that a new row is added per iteration",
    "purrr", "map_vec", "Iterate across a vector and return a vector of values of the same length",
    "purrr", "pluck", "Extract a list item from a list",
    "readr", "read_csv", "Read a tabular csv file into R as a tibble data frame",
    "readr", "read_lines", "Read an atomic vector into R",
    "readr", "read_rds", "Read an RDS file into R",
    "readr", "write_csv", "Write a data frame to your hard drive as a csv file",
    "readr", "write_lines", "Write an atomic vector to your hard drive as a txt file",
    "readr", "write_rds", "Write a data object to your hard drive as an RDS file",
    "readxl", "excel_sheets", "Return the names of worksheets in an Excel file",
    "readxl", "read_excel", "Read an Excel worksheet into R",
    "remotes", "install_github", "Install an R package directly from a GitHub repository.",
    "rlang", "set_names", "Assign names to values in a vector or items in a list",
    "rmapshaper", "ms_simplify", "Reduce the number of nodes in a polygon by a set proportion",
    "sf", "st_area", "Calculate the area of a polygon shapefile",
    "sf", "st_as_sf", "Convert a data frame to an sf object",
    "sf", "st_bbox", "Get the bounding box of a shapefile or create a bounding box from scratch",
    "sf", "st_buffer", "Create a buffer (shapefile) that extends the boundary of a target shapefile by a given distance",
    "sf", "st_cast", "Convert a geometry from one type to another",
    "sf", "st_centroid", "Calculate the geographic center of a set of features",
    "sf", "st_combine", "Combine multiple geometries into a single geometry",
    "sf", "st_convex_hull", "Generate a minimum convex polygon for a set of points (the smallest shape that will enclose each point in which no angle is greater than 180 degrees)",
    "sf", "st_coordinates", "Extract coordinates from an sf object as a matrix",
    "sf", "st_crop", "A type of filtering spatial join in which you subset a target shapefile to the extent of a source shapefile or bounding box",
    "sf", "st_crs", "Get the CRS of a shapefile",
    "sf", "st_difference", "A type of filtering spatial join in which you remove portions of a target shapefile that overlap with a source shapefile",
    "sf", "st_distance", "Calculate the pairwise distance between features in a shapefile (or between different shapefiles)",
    "sf", "st_drop_geometry", "Remove the geometry column from an sf file and (thus) convert to a data frame",
    "sf", "st_filter", "Conduct a filtering join (i.e., subset geometries) of a target table relative to the geometry of a source table",
    "sf", "st_geometry", "Print or extract just the geometry column (and CRS) of an sf object.",
    "sf", "st_geometry_type", "Return the type of geometry present in an sf object",
    "sf", "st_intersection", "A type of mutating *or* filtering spatial join in which you maintain only portions of a target shapefile that overlap with a source shapefile",
    "sf", "st_is_valid", "A logical test to determine if a feature in a polygon shapefile is valid",
    "sf", "st_join", "Conduct a mutating join of a target table relative to the geometry of a source table",
    "sf", "st_linestring", "Convert a matrix to a linestring geometry object",
    "sf", "st_make_valid", "Fix invalid features in a polygon shapefile",
    "sf", "st_point", "Convert a vector of coordinates to a single point",
    "sf", "st_polygon", "Convert a list to a polygon geometry object",
    "sf", "st_read", "Read in a simple features or other GIS shapefile",
    "sf", "st_set_crs", "Set the CRS for a spatial object in which it is absent",
    "sf", "st_sf", "Convert a simple features column object to an sf object",
    "sf", "st_sfc", "Store a geometry in a simple features column object",
    "sf", "st_simplify", "Reduce the resolution (level of detail) of a shapefile by removing nodes that are within a given distance of each other.",
    "sf", "st_transform", "Transform the CRS of a shapefile to a different CRS",
    "sf", "st_union", "Dissolve boundaries between polygons",
    "spatstat.geom", "as.owin", "Determine the observation window for a point pattern object",
    "spatstat.geom", "ppp", "Generate a point pattern object",
    "stars", "st_as_stars", "Convert an object which is not stars to one which is",
    "stats", "density", "Calculate the probability density of values in a set",
    "stats", "median", "Calculate the median value of a numeric vector and return as a one-value double numeric or integer vector",
    "stats", "sd", "Calculate the standard deviation of a numeric vector and return as a one-value double numeric vector",
    "stats", "setNames", "Set the names within an object",
    "stats", "var", "Calculate the variance of a numeric vector and return as a one-value double numeric vector",
    "stringr", "str_c", "Concatenate strings, with or without (default) a separator",
    "stringr", "str_detect", "Logical test of whether a pattern (string) is contained within a character value",
    "stringr", "str_remove", "Remove part of a string based on a search pattern",
    "stringr", "str_replace", "Replace a given pattern in a string with a new pattern",
    "stringr", "str_to_sentence", "Convert a string to sentence case (first letter capitalized)",
    "stringr", "str_to_title", "Convert a string to title case (first letter of each word capitalized)",
    "terra", "aggregate", "Combine adjacent raster cells into larger cells by applying a summary function.",
    "terra", "as.polygons", "Convert a SpatVector or raster to polygon geometries.",
    "terra", "categories", "Generate a categorical raster",
    "terra", "classify", "Classify or reclassify a raster",
    "terra", "crop", "Subset a raster to a new spatial extent (e.g., a bounding box)",
    "terra", "distance", "Calculate the distance from a shapefile or cells in a raster that are not NA",
    "terra", "extract", "Extract raster values to a shapefile based on location",
    "terra", "global", "Calculate a summary statistic across each cell in a raster",
    "terra", "mask", "A type of join in which you convert all cells in a target raster to NA if they are outside of a source object (e.g., a polygon shapefile or SpatVector)",
    "terra", "plot", "Apply a base R-style plot to a terra raster object",
    "terra", "project", "Transform the CRS of a raster",
    "terra", "rast", "Read in a raster object, create a raster object from scratch, or convert a list of raster objects to a raster stack",
    "terra", "rasterize", "Convert a shapefile to a raster",
    "terra", "res", "Return or assign the resolution (cell size) of a raster.",
    "terra", "resample", "Resample the cells of a raster to fit the same resolution and extent of another",
    "terra", "shade", "Generate a hillshade raster",
    "terra", "spatSample", "Generate random or regular sampling points within a raster",
    "terra", "terrain", "Calculate the slope and aspect (and more!) for an elevation raster",
    "terra", "vect", "Convert an sf object to a SpatVector (or create a SpatVector from scratch)",
    "tibble", "as_tibble", "Convert a data frame (and some other non-tibble objects!) to a tibble data frame",
    "tibble", "tibble", "Column-wise creation of a tibble data frame",
    "tibble", "tribble", "Row-wise creation of a tibble data frame",
    "tidyr", "drop_na", "Remove rows that contain NA values",
    "tidyr", "pivot_longer", "Convert a data frame from wide to long format",
    "tidyr", "pivot_wider", "Convert a data frame from long to wide format",
    "tidyr", "replace_na", "Replace an NA value in a vector with a different value",
    "tidyr", "separate", "Separate a single column into multiple columns by a delimiter",
    "tidyr", "unite", "Combine columns in a data frame to create a single column",
    "tidyselect", "everything", "Used in combination with select, this selects all but the specified columns.",
    "tidyselect", "matches", "When used with select, this allows you to subset names with string matching",
    "tidyselect", "where", "Select a variable with a function that returns `TRUE` or `FALSE`",
    "tidyverse", "tidyverse_packages", "Generate a character vector of package names in the tidyverse metapackage",
    "tidyverse", "tidyverse_update", "Update packages in the tidyverse metapackage",
    "tmap", "tm_basemap", "Add a basemap layer to an interactive tmap",
    "tmap", "tm_borders", "Add a layer to a tmap that represents the borders of a polygon shapefile",
    "tmap", "tm_dots", "Add a points layer to a tmap",
    "tmap", "tm_layout", "Define the layout of a tmap",
    "tmap", "tm_legend", "Configure a layer's legend (title, position, frame, orientation) in tmap v4.",
    "tmap", "tm_polygons", "Add a polygon layer to a tmap",
    "tmap", "tm_pos_in", "Position a tmap v4 legend or component inside the map frame.",
    "tmap", "tm_pos_out", "Position a tmap v4 legend or component outside the map frame.",
    "tmap", "tm_raster", "Add a raster layer to a tmap",
    "tmap", "tm_rgb", "Add a raster layer (used here as an image file) to a tmap",
    "tmap", "tm_scale", "Define the default (auto-selected) visual-variable scale for a tmap v4 layer.",
    "tmap", "tm_scale_categorical", "Define a categorical (discrete/qualitative) visual-variable scale for a tmap v4 layer.",
    "tmap", "tm_scale_continuous", "Define a continuous visual-variable scale for a tmap v4 layer.",
    "tmap", "tm_shape", "Define the shape that is the source of a tmap layer",
    "tmap", "tm_title", "Add a map title in tmap v4 (replaces tm_layout(main.title = ...)).",
    "tmap", "tm_view", "Set the view of an interactive tmap (e.g., zoom level)",
    "tmap", "tmap_mode", "Set a tmap to either \"plot\" (static map) or \"view\" (interactive map)",
    "tmap", "tmap_options", "Get or set global tmap options for the current session.",
    "tmap", "tmap_providers", "List the basemap providers available to tm_basemap().",
    "units", "drop_units", "Convert a units object to numeric",
    "units", "set_units", "Convert a units object from one type of unit to another (e.g., meters to kilometers or degrees Fahrenheit to degrees Celsius)",
    "utils", "?", "Prefix operator to retrieve the help file for a function",
    "utils", "install.packages", "Download and install one or more packages onto your computer.",
    "utils", "news", "View the version history of a package",
    "utils", "str", "View the structure of a data object"
  )

